---
- name: Ensure dependencies are installed.
  sudo: True
  apt:
    pkg: curl
    state: installed

- name: Ensure PCP is installed
  sudo: True
  apt:
    pkg: pcp
    state: installed

- name: Ensure pcpwebd is installed
  sudo: True
  apt:
    pkg: pcp-webapi
  when: pcp_install_webapi
